# Generated by Django 4.1.7 on 2023-02-17 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_all_words'),
    ]

    operations = [
        migrations.DeleteModel(
            name='all_words',
        ),
    ]
