# Generated by Django 4.1.7 on 2023-02-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_delete_all_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
